In [3]:
import numpy as np

In [4]:
np_vector = np.array([1,2,3,4], dtype = np.int)
print(np_vector)

[1 2 3 4]


/var/folders/0d/1bv81_wx59994zr7103p9lf00000gn/T/ipykernel_3743/3592754581.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_vector = np.array([1,2,3,4], dtype = np.int)


In [5]:
[np_vector.shape, np_vector.size, np_vector.dtype, np_vector.ndim]

[(4,), 4, dtype('int64'), 1]

In [6]:
np_matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype = np.int64)

In [7]:
print(np_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 4.1.2 함수를 이용해 객체 생성하는 법

In [8]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.arange(0,9) #[start,stop]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [12]:
np.random.uniform(0,1,10)
# 0 부터 1까지 정규분포를 뽑아놓고 

array([0.53873886, 0.72493657, 0.13739359, 0.27888372, 0.52684844,
       0.33641905, 0.88550299, 0.78194027, 0.53939065, 0.39717634])

In [15]:
np.random.normal(0,1,10)
# 표준정규분포 - 음수가 나올수도

array([ 1.82079944, -0.64530775, -1.04354416, -0.5054184 ,  0.93792575,
       -0.55996319,  0.06140192, -0.47515529, -2.69016562,  0.75520221])

In [16]:
np.identity(4)
#정사각형으로 생긴 행렬인데 대각선만 1, 다른건 다 0 = identical matrix (단위행렬)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.diag([1,2,3,4])
# 위에랑 똑같이 나오는데 diagonal 값을 1말고 다른걸로 바꿀 수 있다

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.eye(N=3, M=5, k=0) #k는 어떤 역할을 하는가?
#k=1 이면 1행2열에서 시작해서 미는것. so k의 역할은 미는것

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [20]:
np.eye(N=3, M=5, k=1) 

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [21]:
np.empty((5,5))

array([[1.28822975e-231, 1.28822975e-231, 9.38724727e-323,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [2.14321575e-312, 1.28822975e-231, 1.28822975e-231,
        5.43472210e-323, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [23]:
np.linspace(1,100,33)
#행렬 형태가 아니고 linear space. 1~100까지를 33개로 쪼개서 


array([  1.     ,   4.09375,   7.1875 ,  10.28125,  13.375  ,  16.46875,
        19.5625 ,  22.65625,  25.75   ,  28.84375,  31.9375 ,  35.03125,
        38.125  ,  41.21875,  44.3125 ,  47.40625,  50.5    ,  53.59375,
        56.6875 ,  59.78125,  62.875  ,  65.96875,  69.0625 ,  72.15625,
        75.25   ,  78.34375,  81.4375 ,  84.53125,  87.625  ,  90.71875,
        93.8125 ,  96.90625, 100.     ])

### 4.1.3 함수에 기존 객체를 넣어서 생성하는 방법

In [26]:
np_matrix = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype = np.int)
np_matrix

/var/folders/0d/1bv81_wx59994zr7103p9lf00000gn/T/ipykernel_3743/1561251790.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_matrix = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype = np.int)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
np.ones_like(np_matrix)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.zeros_like(np_matrix)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
np.diag(np_matrix, k=1)

array([ 2,  7, 12])

## 4.2 Reshape

In [30]:
np_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]], dtype = np.int)
np_matrix

/var/folders/0d/1bv81_wx59994zr7103p9lf00000gn/T/ipykernel_3743/545666305.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  [9, 10, 11, 12]], dtype = np.int)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
np_matrix.reshape(2, -1) # Q. -1은 어떤 역할을 하는가?
# 하나의 행을 잡고 -1 하면 알아서 넣어준다

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## 4.3 Indexing&slicing를 통한 접근과 변경

### 4.3.1 Indexing

In [33]:
Z[0, :]
Z[2:, 2:]
# 차이 파악하기

NameError: name 'Z' is not defined

## 4.5 복수 객체 Operation

### 4.5.1 1-dim array

In [37]:
np_vector_1 = np.arange(1,13, dtype = np.string)
np_vector_2 = np.arange(13,25, dtype = np.int)

AttributeError: module 'numpy' has no attribute 'string'

## 4.6 Broadcasting

In [39]:
np_matrix_1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype = np.int)
np_matrix_1

/var/folders/0d/1bv81_wx59994zr7103p9lf00000gn/T/ipykernel_3743/2671290334.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_matrix_1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype = np.int)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
np_matrix_2 = np.arange(13,25, dtype=np.int).reshape(3,4) #3x4
np_matrix_2

/var/folders/0d/1bv81_wx59994zr7103p9lf00000gn/T/ipykernel_3743/656529149.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_matrix_2 = np.arange(13,25, dtype=np.int).reshape(3,4) #3x4


array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [43]:
np_matrix_1 + np_matrix_2

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [45]:
np_matrix_1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np_matrix_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
np_scalar_1 = int(3)

In [47]:
np_scalar_1

3

In [49]:
np_vector_3 = np.array([1,2,3,4])
np_vector_4 = np.array([1,2,3])

### 4.7.2 np.argmax/min

In [ ]:
np.argmax(np_vector_3)
#arg세모(x)
#세모 = max
#np_vector_3 중에 젤 큰걸 찾아라