# Numpy 기본 사용법 - 동빈나 [Python 데이터 분석과 이미지 처리]

## Numpy 기본 사용법

In [1]:
import numpy as np

In [3]:
# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [5]:
# 4x4 크기의 2차원 배열을 만들고, 모든 값들이 0으로 초기화 되어있고, 그 값들이 다 float
array2 = np.zeros((4,4), dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# 값이 1로 초기화, 문자열로
array3 = np.ones((3,3), dtype=str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [7]:
# 0 부터 9까지 랜덤하게 초기화 된 배열 만들기
# 3x3 크기의 배열, 0~9사이의 숫자
array4 = np.random.randint(0,10,(3,3))
print(array4)

[[5 1 2]
 [0 2 3]
 [7 8 9]]


In [8]:
# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열 (표준정규분포)
array5 = np.random.normal(0,1,(3,3))
print(array5)

[[-1.2244386   0.36108121  0.16157211]
 [ 0.73116654 -0.72087137 -0.26938426]
 [-0.3372711   0.65649974  0.08115187]]


In [14]:
# Numpy 배열 합치기

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [15]:
# Numpy 배열 형태 바꾸기

array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))
print(array2)

[[1 2]
 [3 4]]


In [17]:
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
print(array2)

# 세로축을 기준으로 합치기
array3 = np.concatenate([array1, array2], axis=0)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [18]:
# 배열 나누기

array = np.arange(8).reshape(2,4)
print(array)
# split 함수 사용, 나누는 기준은 index [2], 그리고 그 index[2]는 열을 의미한다는 axis=1
left, right = np.split(array, [2], axis=1)
print(left.shape)
print(right.shape)
print(left)
print(right)


[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


## Numpy의 기본 연산

In [20]:
# 1. Numpy의 상수 연산 : 더하기

array = np.random.randint(1,10, size=4).reshape(2,2)
print(array)
result_array = array * 10
print(result_array)

[[7 6]
 [9 1]]
[[70 60]
 [90 10]]


In [23]:
# 서로 다른 형태의 배열 연산 => 행 우선으로 수행됨 (Broadcasting)

array1 = np.arange(4).reshape(2,2)  # (2 x 2)
print(array1)
array2 = np.arange(2)             # (1 x 2)
print(array2)

array3 = array1 + array2
print(array3)


[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [28]:
# Broadcasting = 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

array1 = np.arange(0,8).reshape(2,4)
print(array1)
array2 = np.arange(0,8).reshape(2,4)
print(array2)
print("----")
array3 = np.concatenate([array1, array2], axis=0)
print(array3)
array4 = np.arange(0,4).reshape(4,1)
print(array4)
#broadcasting
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
----
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [31]:
# 마스킹 연산 : 각 원소에 대해 체크

array1 = np.arange(16).reshape(4,4)
print(array1)
print("---")
array2 = array1 < 10
print(array2)
print("---")

#마스킹 연산 활용 
array1[array2] = 100 # 조건을 만족하는 데이터만 작업을 해주겠다
# 10보다 작은 원소만 선택해서 (True인 애들) 100으로 바꿔주겠다는 뜻
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
---
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
---
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [35]:
# Numpy 집계 함수

array = np.arange(16).reshape(4,4)
print(array)
print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

# 각 열에 대해 집계할 수도 있음
print("첫번째 열 합계: ", np.sum(array, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
최대값: 15
최소값: 0
합계: 120
평균값: 7.5
첫번째 열 합계:  [24 28 32 36]


## Numpy의 활용

### Numpy의 저장과 불러오기

In [38]:
# 단일 객체 저장 및 불러오기
array = np.arange(0,10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
# 복수 객체 저장 및 불러오기

array1 = np.arange(0,10)
array2 = np.arange(10,20)
np.savez('saved.npz', array1=array1, array2=array2) #savez : 복수의 객체를 파일로 저장할 때 사용, 각각의 객체명도 따로 저장가능

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


### Numpy 원소의 정렬

In [40]:
# 원소 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])

array.sort() #기본이 오름차순
print(array)

#내림차순 정렬
print(array[::-1])

[ 1  3  5  9 10]
[10  9  5  3  1]


In [42]:
# 각 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(array)

array.sort(axis=0)
#정렬할때 기준을 행으로 삼게 되면, 각각의 열을 봤을때 더 큰 행이 아랫쪽으로 내려가게 된다
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


### 균일한 간격으로 데이터 생성 : linspace

In [43]:
array = np.linspace(0, 10, 5) # 0부터 10 사이를 5개의 데이터가 채우기
print(array)

[ 0.   2.5  5.   7.5 10. ]


### 난수(random수)의 재연 (실행마다 결과 동일)

In [47]:
print(np.random.randint(0, 10, (2,3)))

[[7 9 7]
 [8 9 8]]


In [48]:
# seed를 사용해서 어떤 값을 기준으로 난수를 만들건지 설정 가능
np.random.seed(7)
print(np.random.randint(0, 10, (2,3)))
# 실행할때마다 난수의 결과가 동일

[[4 9 6]
 [3 3 7]]


### Numpy 배열 객체 복사

In [52]:
array1 = np.arange(0, 10)
print("array1: ", array1)
array2 = array1 #동일한 주소 가르킴
print("array2: ", array2)
array2[0] = 99
print("array1: ", array1)

# numpy 자체에서는 array1&2 같은 주소 가르키고 있기 때문에,
# array2를 수정하더라도 array1도 같이 바뀐다!!

array1:  [0 1 2 3 4 5 6 7 8 9]
array2:  [0 1 2 3 4 5 6 7 8 9]
array1:  [99  1  2  3  4  5  6  7  8  9]


In [53]:
# 이런 사태를 예방하기 위해서 객체를 복사해서 사용한다

array1 = np.arange(0, 10)
print("array1: ", array1)
array2 = array1.copy()           #복사
print("array2: ", array2)
array2[0] = 99                   #array1에 영향 끼치지 않음
print("array1: ", array1)

array1:  [0 1 2 3 4 5 6 7 8 9]
array2:  [0 1 2 3 4 5 6 7 8 9]
array1:  [0 1 2 3 4 5 6 7 8 9]


### 중복된 원소 제거

In [54]:
# unique 사용
array = np.array([1,1,2,2,2,3,3,4])
print(np.unique(array))

[1 2 3 4]
